language: go
os: linux-ppc64le
dist: xenial
arch: ppc64le
sudo: false
go: "1.14.x"
  
env: RESTIC_TEST_FUSE=0 RESTIC_TEST_CLOUD_BACKENDS=0
cache: 
    directories:
      - $HOME/.cache/go-build
      - $HOME/gopath/pkg/mod
  }

script:
    - unset GOPATH,
    - git clone https://github.com/restic/restic,
    - cd restic,
    - go build ./cmd/restic,
    - ./restic version,
    - go test ./...
    
    #
